MOSZE Task 3: Fighter Class Reference
Fighter Class Reference
#include <Fighter.h>
Public Member Functions
Fighter (std::string iname, int ihp, int idmg, double acd)
~Fighter ()
int getHP () const
int getDMG () const
double getCD () const
std::string getName () const
void duel (Fighter *enemy)
Static Public Member Functions
static Fighter parseUnit (std::string fname)
Friends
std::ostream & operator<< (std::ostream &os, const Fighter &fi)
Detailed Description
Definition at line 7 of file Fighter.h.
Constructor & Destructor Documentation
Fighter()
Fighter::Fighter (std::string iname, int ihp, int idmg, double acd) inline
A class that contains the attributes of fighters. They have HP, Damage, attackcooldown which they get from input, and their own name.
Definition at line 41 of file Fighter.h.
Referenced by parseUnit().
~Fighter()
Fighter::~Fighter () inline
Definition at line 42 of file Fighter.h.
Member Function Documentation
duel()
void Fighter::duel (Fighter * enemy)
Method for 2 characters fighting.
Definition at line 14 of file Fighter.cpp.
References getCD(), getHP(), and getName().
Referenced by getName(), and main().
getCD()
double Fighter::getCD () const inline
Definition at line 47 of file Fighter.h.
Referenced by duel().
getDMG()
int Fighter::getDMG () const inline
Definition at line 46 of file Fighter.h.
Referenced by operator<<().
getHP()
int Fighter::getHP () const inline
Definition at line 45 of file Fighter.h.
Referenced by duel(), and operator<<().
getName()
std::string Fighter::getName () const inline
Definition at line 48 of file Fighter.h.
References duel(), operator<<, and parseUnit().
Referenced by duel(), and operator<<().
parseUnit()
Fighter Fighter::parseUnit (std::string fname) static
Static method to process input json files.
Definition at line 61 of file Fighter.cpp.
References Fighter().
Referenced by getName(), and main().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Fighter & fi) friend
Operator overload to make the class printable.
Definition at line 54 of file Fighter.cpp.
Referenced by getName().
The documentation for this class was generated from the following files:
Fighter.h
Fighter.cpp